python:
  - "2.7"

script:
  - PYTHONPATH=. python tools/test/config_test/config_test.py
  - py.test tools/test/toolchains/api.py
  - python tools/build_travis.py
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - virtualenv --no-site-packages venv
  - source venv/bin/activate
  - python --version
install:
  - pip install colorama
  - pip install prettytable
  - pip install jinja2
  - pip install pytest
  - pip install virtualenv
